### ISSUE TITLE
com.unboundid.ldap.sdk.DN.isValidDN changed between 2.3.6 and 2.3.7 and later versions

### ISSUE THREAD

**Issue by zrinyi** [UnboundID/ldapsdk#19]
In version 2.3.6 and older versions the tests below were fine but since version 2.3.7 they fail (the test values are accepted as valid DNs). Is this on purpose or is a bug?

```
	@Test
	public void isValiDNTest_4(){
		String str = "cn=";		
		System.out.println("isValiDNTest_4="+com.unboundid.ldap.sdk.DN.isValidDN(str));
		assertFalse(StringUtil.isValidDN(str));
	}

	@Test
	public void isValiDNTest_5(){
		String str = "cn=, ou= test, o=VGR";
		System.out.println("isValiDNTest_5="+com.unboundid.ldap.sdk.DN.isValidDN(str));
		assertFalse(StringUtil.isValidDN(str));
	}

```
Outputs:
isValiDNTest_4=true
isValiDNTest_5=true

**Comment by dirmgr** [comment]
The change was intentional. There is nothing wrong with an empty RDN value, as long as the associated syntax allows it. It was a bug that earlier versions of the LDAP SDK wouldn't ever accept empty values.

You could still argue that these DNs are invalid since the cn attribute uses the directory string syntax, which does not permit empty values. However, the LDAP SDK doesn't necessarily know that the cn attribute has a directory string syntax. Further, even if it did, some directory servers don't enforce that restriction, so the LDAP SDK should be prepared to encounter empty directory string values.

**Comment by zrinyi** [comment]
So if I want to mimic the  old behaviour using the new version of the SDK, I need to check if the string is a valid DN and if true check that there isn't any  empty RDN's, right?

**Comment by dirmgr** [comment]
Yes. That is correct.

**Comment by zrinyi** [comment]
Ok.Thanks!
